# Generated by Django 4.1.9 on 2024-01-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20200727_1906"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("certification_date", models.DateField()),
                ("certificate_file", models.FileField(upload_to="certificates/")),
            ],
        ),
    ]
